development:
  adapter: postgresql
  database: bitcoin_watcher_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bitcoin_watcher_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bitcoin_watcher_production
  pool: 5
  timeout: 5000
